name: 'greenery'
version: '1.0.0'
config-version: 2

profile: 'greenery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"

models:
  greenery:
    example:
      +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table

  post-hook: # will be applied to all models
   - "grant select on {{ this }} to reporting"

on-run-end: # will be applied at the end of a run
  - "grant usage on schema {{ target.schema }} to group reporting"
